name: Build on Ubuntu

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libnvidia-ml-dev
          
      - name: Build
        run: make all

      - name: Package all binaries into tar.gz
        run: |
          VERSION_TAG=${GITHUB_REF##*/}
          mkdir -p dist
          tar -czvf dist/nvidia-gpu-ROP-count-linux-${VERSION_TAG}.tar.gz -C bin .

      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
