name: Build on Ubuntu

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libnvidia-ml-dev
          
      - name: Build
        run: make all

      - name: Package all binaries into tar.gz and generate checksums
        run: |
          # create the tar.gz file
          VERSION_TAG=${GITHUB_REF##*/}
          # create the checksum file for all binaries, to be included in the tar.gz file
          cd bin
          sha256sum * > checksums-amd64-${VERSION_TAG}.sha256
          cd ..
          mkdir -p dist
          tar --exclude='.gitkeep' -czvf dist/nvidia-gpu-ROP-count-linux-amd64-${VERSION_TAG}.tar.gz -C bin .
          # create the checksum file for the tar.gz file
          cd dist
          sha256sum nvidia-gpu-ROP-count-linux-amd64-${VERSION_TAG}.tar.gz > release-package-checksum-amd64-${VERSION_TAG}.sha256
          cd ..
        
      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.tar.gz
            dist/*.sha256
